apiVersion: v2
name: inventario-app
description: A Helm chart for Ivent App
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: infra-nats
    version: 0.1.0
    repository: "file://charts/infra-nats"
  - name: ms-gateway
    version: 0.1.0
    repository: "file://charts/ms-gateway"
  - name: ms-inventario
    version: 0.1.0
    repository: "file://charts/ms-inventario"