global:
  namespace: "inventario-app"
  nats:
    url: "nats://nats:4222"
  env:
    PORT: 3000
  database:
    postgres:
      user: "jorge_admin"
      pass: "ivent_secure_pass_2024"
      dbName: "inventario_db"
      host: "postgres-service"
  jwt:
    seed: "mi_semilla_secreta_para_tokens"

# Activaci√≥n de servicios
infra-nats:
  enabled: true

ms-gateway:
  enabled: true