apiVersion: v1
kind: Secret
metadata:
  name: ivent-global-secrets
  namespace: inventario-app
type: Opaque
data:
  POSTGRES_USER: am9yZ2VfYWRtaW4=
  POSTGRES_PASSWORD: aXZlbnRfc2VjdXJlX3Bhc3NfMjAyNA==
  POSTGRES_DB: aW52ZW50YXJpb19kYg==
  JWT_SECRET: bWlfc2VtaWxsYV9zZWNyZXRhX3BhcmFfdG9rZW5z