enabled: true
msName: ms-gateway
replicaCount: 1

image:
  repository: jorgeas/ivent-ms-gateway
  tag: latest

global:
  namespace: "inventario-app"
  env:
    PORT: 3000
  nats:
    url: "nats://nats:4222"