{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msName }}-config
  namespace: {{ .Values.global.namespace }}
data:
  PORT: {{ .Values.global.env.PORT | quote }}
  NATS_URL: {{ .Values.global.nats.url | quote }}
  # Host del servicio de base de datos que definiremos abajo
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
{{- end }}