{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.msName }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.msName }}
  template:
    metadata:
      labels:
        app: {{ .Values.msName }}
    spec:
      containers:
        - name: {{ .Values.msName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.global.env.PORT }}
          envFrom:
            - configMapRef:
                name: {{ .Values.msName }}-config
          env:
            # Variables que TypeORM leer√° del Secret Global
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ivent-global-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ivent-global-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ivent-global-secrets
                  key: POSTGRES_DB
{{- end }}