apiVersion: v1
kind: Secret
metadata:
  name: ivent-db-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # AÃ±adimos .Values.global antes de database
  POSTGRES_USER: {{ .Values.global.database.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.database.postgres.pass | b64enc }}
  POSTGRES_DB: {{ .Values.global.database.postgres.dbName | b64enc }}