apiVersion: v1
kind: Secret
metadata:
  name: ivent-db-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.database.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.database.postgres.pass | b64enc | quote }}
  POSTGRES_DB: {{ .Values.global.database.postgres.dbName | b64enc | quote }}