apiVersion: v1
kind: Service
metadata:
  name: ms-inventario
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: ms-inventario
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.global.env.PORT }}