apiVersion: v1
kind: Secret
metadata:
  name: ivent-global-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # Codificamos los valores de values.yaml en base64 autom√°ticamente
  POSTGRES_USER: {{ .Values.global.database.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.database.postgres.pass | b64enc }}
  POSTGRES_DB: {{ .Values.global.database.postgres.dbName | b64enc }}
  JWT_SECRET: {{ .Values.global.jwt.seed | b64enc }}