apiVersion: v2
name: jenkins
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: jenkins
    version: 5.8.7
    repository: https://charts.jenkins.io