controller:
  
  installPlugins: false 
  
  admin:
    password: "admin"
  
  serviceType: NodePort
  nodePort: 32000

  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  
  
  sidecars:
    configAutoReload:
      enabled: false

persistence:
  enabled: true
  size: 10Gi
  storageClass: "microk8s-hostpath"