{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msName }}-config
  namespace: {{ .Values.global.namespace }}
data:
  PORT: {{ .Values.global.env.PORT | quote }}
  NATS_URL: {{ .Values.global.nats.url | quote }}
{{- end }}