{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.msName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.global.env.PORT }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.msName }}
{{- end }}